version: "3.8"

services:
  strapi:
    image: tadeuaugustovilela/strapi-ledscore:latest
    container_name: strapi-ledscore
    ports:
      - "1337:1337"
    volumes:
    - ./strapi-data:/opt/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: leds_core
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: senhapica123
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - ledsnet

  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    networks:
      - ledsnet

  db:
    image: postgres:17
    container_name: leds-postgres
    environment:
      POSTGRES_DB: leds_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhapica123
    volumes:
      - ./leds_core.backup:/docker-entrypoint-initdb.d/leds_core.backup
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ledsnet

networks:
  ledsnet:
    driver: bridge
