version: "3.8"

services:
  strapi:
    image: tadeuaugustovilela/strapi-ledscore:latest
    container_name: strapi-ledscore
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-data:/opt/app
    environment:
      APP_KEYS: ${APP_KEYS}  # Ex: "sua_app_key1,sua_app_key2"
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME:-leds_core}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - ledsnet

  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    networks:
      - ledsnet

  db:
    image: postgres:17
    container_name: leds-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-leds_core}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./leds_core.backup:/docker-entrypoint-initdb.d/leds_core.backup
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ledsnet

networks:
  ledsnet:
    driver: bridge

volumes:
  postgres-data:
